--GENERAR 500 SOCIOS    
/*
   500 JUGADORES
   
   10%: Mayores de 70
   15%: Entre 60 y 69
   40%: Entre 40 y 59       
   30%:Entre 25 y 40
   5%: Menores de 25
*/
SET SERVEROUTPUT ON;
DECLARE
    TYPE REFCURSOR IS REF CURSOR;
    V_NOMBRE NVARCHAR2(80);
    V_APATERNO NVARCHAR2(60);
    V_ID NUMBER(4,0);
    V_EDAD NUMBER(6,0);
    CURSOR C1 IS
    SELECT RUT, DV, FENAC FROM (SELECT RUT, DV, FENAC FROM CLIENTE_EXT WHERE (SYSDATE - FENAC)/365 >= 70) C WHERE ROWNUM <= 50;
    CURSOR C2 IS
    SELECT RUT, DV, FENAC FROM (SELECT RUT, DV, FENAC FROM CLIENTE_EXT WHERE (SYSDATE - FENAC)/385 >= 60 AND (SYSDATE - FENAC)/365 < 70) C WHERE ROWNUM <= 75;
    CURSOR C3 IS
    SELECT RUT, DV, FENAC FROM (SELECT RUT, DV, FENAC FROM CLIENTE_EXT WHERE (SYSDATE - FENAC)/365 >= 40 AND (SYSDATE - FENAC)/365 < 60) C WHERE ROWNUM <= 200;
    CURSOR C4 IS
    SELECT RUT, DV, FENAC FROM (SELECT RUT, DV, FENAC FROM CLIENTE_EXT WHERE (SYSDATE - FENAC)/365 >= 25 AND (SYSDATE - FENAC)/365 < 40) C WHERE ROWNUM <= 150;
    CURSOR C5 IS
    SELECT RUT, DV, FENAC FROM (SELECT RUT, DV, FENAC FROM CLIENTE_EXT WHERE (SYSDATE - FENAC)/365 >= 12 AND (SYSDATE - FENAC)/365 < 25) C WHERE ROWNUM <= 25;
BEGIN

    INSERT INTO PSO_JUGADOR_ATP
    SELECT * FROM JUGADOR_ATP;
    
    FOR C IN C1 LOOP       
       SELECT RNK, NOMBRE, APATERNO INTO V_ID, V_NOMBRE, V_APATERNO FROM (SELECT RNK, NOMBRE, APATERNO FROM PSO_JUGADOR_ATP ORDER BY DBMS_RANDOM.RANDOM) A WHERE ROWNUM < 2;
       
       SELECT (SYSDATE - C.FENAC)/365 INTO V_EDAD FROM DUAL;
       DBMS_OUTPUT.PUT_LINE('EDAD:' || V_EDAD || ',RUT:' || C.RUT || ',DV:' || C.DV || ', Nombre:' || V_NOMBRE || ',fenac:' || C.FENAC);
        
       PKG_SOCIO_CRUD.PRC_CREAR_SOCIO_EXT(C.RUT,C.DV,V_NOMBRE, V_APATERNO, NULL, 'M', C.FENAC, null, null, 6);
        
       DELETE FROM PSO_JUGADOR_ATP WHERE RNK = V_ID;
    END LOOP;
    
    FOR C IN C2 LOOP       
       SELECT RNK, NOMBRE, APATERNO INTO V_ID, V_NOMBRE, V_APATERNO FROM (SELECT RNK, NOMBRE, APATERNO FROM PSO_JUGADOR_ATP ORDER BY DBMS_RANDOM.RANDOM) A WHERE ROWNUM < 2;
       
       SELECT (SYSDATE - C.FENAC)/365 INTO V_EDAD FROM DUAL;
       DBMS_OUTPUT.PUT_LINE('EDAD:' || V_EDAD || ',RUT:' || C.RUT || ',DV:' || C.DV || ', Nombre:' || V_NOMBRE || ',fenac:' || C.FENAC);
        
       PKG_SOCIO_CRUD.PRC_CREAR_SOCIO_EXT(C.RUT,C.DV,V_NOMBRE, V_APATERNO, NULL, 'M', C.FENAC, null, null, 6);
        
       DELETE FROM PSO_JUGADOR_ATP WHERE RNK = V_ID;
    END LOOP;    
    
    FOR C IN C3 LOOP       
       SELECT RNK, NOMBRE, APATERNO INTO V_ID, V_NOMBRE, V_APATERNO FROM (SELECT RNK, NOMBRE, APATERNO FROM PSO_JUGADOR_ATP ORDER BY DBMS_RANDOM.RANDOM) A WHERE ROWNUM < 2;
       
       SELECT (SYSDATE - C.FENAC)/365 INTO V_EDAD FROM DUAL;
       DBMS_OUTPUT.PUT_LINE('EDAD:' || V_EDAD || ',RUT:' || C.RUT || ',DV:' || C.DV || ', Nombre:' || V_NOMBRE || ',fenac:' || C.FENAC);
        
       PKG_SOCIO_CRUD.PRC_CREAR_SOCIO_EXT(C.RUT,C.DV,V_NOMBRE, V_APATERNO, NULL, 'M', C.FENAC, null, null, 6);
        
       DELETE FROM PSO_JUGADOR_ATP WHERE RNK = V_ID;
    END LOOP;
    
    FOR C IN C4 LOOP       
       SELECT RNK, NOMBRE, APATERNO INTO V_ID, V_NOMBRE, V_APATERNO FROM (SELECT RNK, NOMBRE, APATERNO FROM PSO_JUGADOR_ATP ORDER BY DBMS_RANDOM.RANDOM) A WHERE ROWNUM < 2;
       
       SELECT (SYSDATE - C.FENAC)/365 INTO V_EDAD FROM DUAL;
       DBMS_OUTPUT.PUT_LINE('EDAD:' || V_EDAD || ',RUT:' || C.RUT || ',DV:' || C.DV || ', Nombre:' || V_NOMBRE || ',fenac:' || C.FENAC);
        
       PKG_SOCIO_CRUD.PRC_CREAR_SOCIO_EXT(C.RUT,C.DV,V_NOMBRE, V_APATERNO, NULL, 'M', C.FENAC, null, null, 6);
        
       DELETE FROM PSO_JUGADOR_ATP WHERE RNK = V_ID;
    END LOOP;
    
    FOR C IN C5 LOOP       
       SELECT RNK, NOMBRE, APATERNO INTO V_ID, V_NOMBRE, V_APATERNO FROM (SELECT RNK, NOMBRE, APATERNO FROM PSO_JUGADOR_ATP ORDER BY DBMS_RANDOM.RANDOM) A WHERE ROWNUM < 2;
       
       SELECT (SYSDATE - C.FENAC)/365 INTO V_EDAD FROM DUAL;
       DBMS_OUTPUT.PUT_LINE('EDAD:' || V_EDAD || ',RUT:' || C.RUT || ',DV:' || C.DV || ', Nombre:' || V_NOMBRE || ',fenac:' || C.FENAC);
        
       PKG_SOCIO_CRUD.PRC_CREAR_SOCIO_EXT(C.RUT,C.DV,V_NOMBRE, V_APATERNO, NULL, 'M', C.FENAC, null, null, 6);
        
       DELETE FROM PSO_JUGADOR_ATP WHERE RNK = V_ID;
    END LOOP;
END;


TRUNCATE TABLE SOCIO;

SELECT COUNT(1) FROM SOCIO;

SELECT ROUND((SYSDATE - FENAC)/365) FROM SOCIO;

SELECT * FROM SOCIO WHERE (SYSDATE - FENAC)/365 <= 25;

SELECT * FROM SOCIO WHERE (SYSDATE - FENAC)/365 > 25 AND (SYSDATE - FENAC)/365 <= 40;

SELECT COUNT(1) FROM CLIENTE_EXT WHERE (SYSDATE - FENAC)/365 <= 30;

SELECT COUNT(1) FROM CLIENTE_EXT WHERE (SYSDATE - FENAC)/365 >= 50;

SELECT COUNT(1) FROM CLIENTE_EXT WHERE (SYSDATE - FENAC)/365 >= 65;

SELECT * FROM (SELECT NOMBRE, APATERNO, EDAD FROM JUGADOR_ATP ORDER BY DBMS_RANDOM.RANDOM) WHERE ROWNUM < 2;
