CREATE OR REPLACE PACKAGE PKG_SOCIO_CRUD AS

TYPE REFCURSOR IS REF CURSOR;

FUNCTION FNC_LISTA_SOCIOS RETURN REFCURSOR;
PROCEDURE PRC_LISTA_SOCIOS(P_DATA  OUT REFCURSOR);

FUNCTION FNC_OBTIENE_SOCIO(P_IDSOCIO IN NUMBER) RETURN REFCURSOR;
PROCEDURE PRC_OBTIENE_SOCIO(P_IDSOCIO IN NUMBER, P_DATA  OUT REFCURSOR);

PROCEDURE PRC_CREAR_SOCIO(P_RUT IN NUMBER, P_DV IN NUMBER, P_NOMBRES IN NVARCHAR2, P_APATERNO IN NVARCHAR2, P_AMATERNO IN NVARCHAR2, P_SEXO IN varchar2);

END PKG_SOCIO_CRUD;

/


CREATE OR REPLACE PACKAGE BODY PKG_SOCIO_CRUD AS


FUNCTION FNC_LISTA_SOCIOS RETURN REFCURSOR IS
  CUR REFCURSOR;
  BEGIN

        OPEN CUR FOR      
        SELECT *
        FROM SOCIO;

        RETURN CUR;
  END;

PROCEDURE PRC_LISTA_SOCIOS(P_DATA OUT REFCURSOR) IS
  BEGIN
        OPEN P_DATA FOR
        SELECT
        A.IDSOCIO      IDSOCIO,
        A.RUT          RUT,
        A.DV           DV,
        A.NOMBRES      NOMBRES,
        A.APATERNO     APATERNO,
        A.AMATERNO     AMATERNO,
        A.SEXO         SEXO,
        A.FENAC        FENAC,
        A.CORREO       CORREO,
        A.NROCELULAR   NROCELULAR,
        A.TIPOSOCIO    TIPOSOCIO,
        A.IDESTADO     IDESTADO,
        A.FECRE        FECRE,
        A.FEMOD        FEMOD
        FROM SOCIO A;        
  END;

FUNCTION FNC_OBTIENE_SOCIO(P_IDSOCIO IN NUMBER) RETURN REFCURSOR IS
  CUR REFCURSOR;
  BEGIN

        OPEN CUR FOR      
        SELECT *
        FROM SOCIO where IDSOCIO = P_IDSOCIO;

        RETURN CUR;
  END;

PROCEDURE PRC_OBTIENE_SOCIO(P_IDSOCIO IN NUMBER, P_DATA  OUT REFCURSOR) IS
  BEGIN
        OPEN P_DATA FOR
        SELECT
        A.IDSOCIO      IDSOCIO,
        A.RUT          RUT,
        A.DV           DV,
        A.NOMBRES      NOMBRES,
        A.APATERNO     APATERNO,
        A.AMATERNO     AMATERNO,
        A.SEXO         SEXO,
        A.FENAC        FENAC,
        A.CORREO       CORREO,
        A.NROCELULAR   NROCELULAR,
        A.TIPOSOCIO    TIPOSOCIO,
        A.IDESTADO     IDESTADO,
        A.FECRE        FECRE,
        A.FEMOD        FEMOD
        FROM SOCIO A
        WHERE A.IDSOCIO = P_IDSOCIO;
  END;

PROCEDURE PRC_CREAR_SOCIO(P_RUT IN NUMBER, P_DV IN NUMBER, P_NOMBRES IN NVARCHAR2, P_APATERNO IN NVARCHAR2, P_AMATERNO IN NVARCHAR2, P_SEXO IN varchar2) IS
  V_CORR NUMBER;
  BEGIN
    SELECT MAX(IDSOCIO) + 1 INTO V_CORR FROM SOCIO;

    INSERT INTO SOCIO (IDSOCIO,RUT,DV,NOMBRES,APATERNO,AMATERNO,SEXO,FENAC,CORREO,NROCELULAR,TIPOSOCIO,IDESTADO,FECRE,FEMOD)
    VALUES (V_CORR,P_RUT,P_DV,P_NOMBRES,P_APATERNO,P_AMATERNO,P_SEXO,null,null,null,1,1,sysdate,null);

  END;

END PKG_SOCIO_CRUD;

/
