CREATE OR REPLACE PACKAGE PKG_COMUNES AS

TYPE REFCURSOR IS REF CURSOR;

PROCEDURE PRC_CREAR_UF(P_FECHA IN DATE, P_VALOR NUMBER, P_ERRCOD OUT NUMBER, P_ERRMSG OUT VARCHAR2);

END PKG_COMUNES;
/


CREATE OR REPLACE PACKAGE BODY PKG_COMUNES AS

TYPE REFCURSOR IS REF CURSOR;

PROCEDURE PRC_CREAR_UF(P_FECHA IN DATE, P_VALOR NUMBER, P_ERRCOD OUT NUMBER, P_ERRMSG OUT VARCHAR2) IS
  BEGIN
    P_ERRCOD:=0;
    P_ERRMSG:='';

   INSERT INTO TASA_CAMBIO (CODMONEDA, FECAMBIO, TASACAMBIO) VALUES ('UF', P_FECHA, P_VALOR);

  END;

END PKG_COMUNES;
/
