  CREATE GLOBAL TEMPORARY TABLE "PSO_CUOTA" 
   (	"IDSOCIO" NUMBER(10,0), 
	"PERIODO" NUMBER(6,0), 
	"MONTO_BRUTO" NUMBER(12,0), 
	"MONTO_DSCTO" NUMBER(12,0), 
	"MONTO_NETO" NUMBER(12,0), 
	"MONTO_ABONO" NUMBER(12,0), 
	"IDPAGADOR" NUMBER(10,0), 
	"ESTADO" CHAR(3 BYTE), 
	"OBSERVACION" VARCHAR2(255 BYTE), 
	"FECRE" DATE, 
	"FEMOD" DATE
   ) ON COMMIT DELETE ROWS ;
--------------------------------------------------------
--  Constraints for Table PSO_CUOTA
--------------------------------------------------------

  ALTER TABLE "PSO_CUOTA" MODIFY ("IDSOCIO" NOT NULL ENABLE);
  ALTER TABLE "PSO_CUOTA" MODIFY ("PERIODO" NOT NULL ENABLE);
  ALTER TABLE "PSO_CUOTA" MODIFY ("MONTO_BRUTO" NOT NULL ENABLE);
  ALTER TABLE "PSO_CUOTA" MODIFY ("MONTO_DSCTO" NOT NULL ENABLE);
  ALTER TABLE "PSO_CUOTA" MODIFY ("MONTO_NETO" NOT NULL ENABLE);
  ALTER TABLE "PSO_CUOTA" MODIFY ("IDPAGADOR" NOT NULL ENABLE);
  ALTER TABLE "PSO_CUOTA" MODIFY ("OBSERVACION" NOT NULL ENABLE);
  ALTER TABLE "PSO_CUOTA" MODIFY ("FECRE" NOT NULL ENABLE);
