CREATE TABLE "VALOR_CUOTA_SOCIAL" 
(	"IDVALCUOTA" NUMBER(*,0), 
"VALOR" NUMBER(12,4), 
"CODMONEDA" VARCHAR2(3 BYTE), 
"FECRE" DATE, 
"FEINIVIG" DATE, 
"FEFINVIG" DATE, 
"OBSERVACION" VARCHAR2(255 BYTE)
);
   
REM INSERTING into VALOR_CUOTA_SOCIAL
SET DEFINE OFF;
Insert into VALOR_CUOTA_SOCIAL (IDVALCUOTA,VALOR,CODMONEDA,FECRE,FEINIVIG,FEFINVIG,OBSERVACION) values ('1','1,1','UF',to_date('15/10/19','DD/MM/RR'),to_date('25/10/19','DD/MM/RR'),to_date('30/01/20','DD/MM/RR'),null);
Insert into VALOR_CUOTA_SOCIAL (IDVALCUOTA,VALOR,CODMONEDA,FECRE,FEINIVIG,FEFINVIG,OBSERVACION) values ('2','1,3','UF',to_date('15/01/20','DD/MM/RR'),to_date('31/01/20','DD/MM/RR'),to_date('30/03/20','DD/MM/RR'),null);
Insert into VALOR_CUOTA_SOCIAL (IDVALCUOTA,VALOR,CODMONEDA,FECRE,FEINIVIG,FEFINVIG,OBSERVACION) values ('3','0,74','UF',to_date('15/03/20','DD/MM/RR'),to_date('31/03/20','DD/MM/RR'),null,'Cuota durante pandemia');


CREATE UNIQUE INDEX "VALOR_CUOTA_SOCIAL_PK" ON "VALOR_CUOTA_SOCIAL" ("IDVALCUOTA");


ALTER TABLE "VALOR_CUOTA_SOCIAL" MODIFY ("IDVALCUOTA" NOT NULL ENABLE);
ALTER TABLE "VALOR_CUOTA_SOCIAL" MODIFY ("VALOR" NOT NULL ENABLE);
ALTER TABLE "VALOR_CUOTA_SOCIAL" MODIFY ("CODMONEDA" NOT NULL ENABLE);
ALTER TABLE "VALOR_CUOTA_SOCIAL" MODIFY ("FECRE" NOT NULL ENABLE);
ALTER TABLE "VALOR_CUOTA_SOCIAL" ADD CONSTRAINT "VALOR_CUOTA_SOCIAL_PK" PRIMARY KEY ("IDVALCUOTA");
