CREATE TABLE "SOCIO" 
(	"IDSOCIO" NUMBER(10,0), 
	"RUT" NUMBER(10,0), 
	"DV" CHAR(1 BYTE), 
	"NOMBRES" NVARCHAR2(80), 
	"APATERNO" NVARCHAR2(60), 
	"AMATERNO" NVARCHAR2(60), 
	"SEXO" CHAR(1 BYTE), 
	"FENAC" DATE, 
	"CORREO" NVARCHAR2(80), 
	"NROCELULAR" NUMBER(10,0), 
	"TIPOSOCIO" NUMBER(*,0), 
	"IDESTADO" NUMBER(*,0), 
	"FECRE" DATE, 
	"FEMOD" DATE
);

COMMENT ON COLUMN "SOCIO"."IDSOCIO" IS 'Correlativo';
COMMENT ON COLUMN "SOCIO"."RUT" IS 'Cuerpo Rut';
COMMENT ON COLUMN "SOCIO"."DV" IS 'Dv Rut';
COMMENT ON COLUMN "SOCIO"."NOMBRES" IS 'Nombres';
COMMENT ON COLUMN "SOCIO"."APATERNO" IS 'Apellido Paterno';
COMMENT ON COLUMN "SOCIO"."AMATERNO" IS 'Apellido Materno';
COMMENT ON COLUMN "SOCIO"."SEXO" IS 'Sexo';
COMMENT ON COLUMN "SOCIO"."FENAC" IS 'Fecha de nacimiento';
COMMENT ON COLUMN "SOCIO"."CORREO" IS 'Email socio';
COMMENT ON COLUMN "SOCIO"."NROCELULAR" IS 'Numero celular socio';
COMMENT ON COLUMN "SOCIO"."TIPOSOCIO" IS 'Tipo de socio. Socio, Director';
COMMENT ON COLUMN "SOCIO"."IDESTADO" IS 'Estado';
COMMENT ON COLUMN "SOCIO"."FECRE" IS 'Fecha de creacion';
COMMENT ON COLUMN "SOCIO"."FEMOD" IS 'Fecha de modificacion';
   
REM INSERTING into SOCIO
SET DEFINE OFF;
Insert into SOCIO (IDSOCIO,RUT,DV,NOMBRES,APATERNO,AMATERNO,SEXO,FENAC,CORREO,NROCELULAR,TIPOSOCIO,IDESTADO,FECRE,FEMOD) values ('1','1','9','Roger','Federer',null,'M',null,null,null,'1','1',to_date('20/06/20','DD/MM/RR'),null);
Insert into SOCIO (IDSOCIO,RUT,DV,NOMBRES,APATERNO,AMATERNO,SEXO,FENAC,CORREO,NROCELULAR,TIPOSOCIO,IDESTADO,FECRE,FEMOD) values ('2','2','7','Rafael','Nadal',null,'M',null,null,null,'1','1',to_date('20/06/20','DD/MM/RR'),null);
Insert into SOCIO (IDSOCIO,RUT,DV,NOMBRES,APATERNO,AMATERNO,SEXO,FENAC,CORREO,NROCELULAR,TIPOSOCIO,IDESTADO,FECRE,FEMOD) values ('3','3','5','Novak','Djokovic',null,'M',null,null,null,'1','1',to_date('20/06/20','DD/MM/RR'),null);
Insert into SOCIO (IDSOCIO,RUT,DV,NOMBRES,APATERNO,AMATERNO,SEXO,FENAC,CORREO,NROCELULAR,TIPOSOCIO,IDESTADO,FECRE,FEMOD) values ('4','4','3','Stan','Wawrinka',null,'M',null,null,null,'1','1',to_date('20/06/20','DD/MM/RR'),null);
--------------------------------------------------------
--  DDL for Index SOCIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOCIO_PK" ON "SOCIO" ("IDSOCIO");
--------------------------------------------------------
--  Constraints for Table SOCIO
--------------------------------------------------------

ALTER TABLE "SOCIO" MODIFY ("IDSOCIO" NOT NULL ENABLE);
ALTER TABLE "SOCIO" MODIFY ("RUT" NOT NULL ENABLE);
ALTER TABLE "SOCIO" MODIFY ("DV" NOT NULL ENABLE);
ALTER TABLE "SOCIO" MODIFY ("NOMBRES" NOT NULL ENABLE);
ALTER TABLE "SOCIO" MODIFY ("APATERNO" NOT NULL ENABLE);
ALTER TABLE "SOCIO" MODIFY ("SEXO" NOT NULL ENABLE);
ALTER TABLE "SOCIO" MODIFY ("TIPOSOCIO" NOT NULL ENABLE);
ALTER TABLE "SOCIO" MODIFY ("IDESTADO" NOT NULL ENABLE);
ALTER TABLE "SOCIO" MODIFY ("FECRE" NOT NULL ENABLE);
ALTER TABLE "SOCIO" ADD CONSTRAINT "SOCIO_PK" PRIMARY KEY ("IDSOCIO");
