CREATE TABLE "TASA_CAMBIO" 
(	"CODMONEDA" VARCHAR2(3 BYTE), 
"FECAMBIO" DATE, 
"TASACAMBIO" NUMBER(18,6)
);
REM INSERTING into TASA_CAMBIO
SET DEFINE OFF;
Insert into TASA_CAMBIO (CODMONEDA,FECAMBIO,TASACAMBIO) values ('UF',to_date('20/06/20','DD/MM/RR'),'28705,99');
Insert into TASA_CAMBIO (CODMONEDA,FECAMBIO,TASACAMBIO) values ('UF',to_date('19/06/20','DD/MM/RR'),'28706,94');
Insert into TASA_CAMBIO (CODMONEDA,FECAMBIO,TASACAMBIO) values ('UF',to_date('18/06/20','DD/MM/RR'),'28707,9');
Insert into TASA_CAMBIO (CODMONEDA,FECAMBIO,TASACAMBIO) values ('UF',to_date('17/06/20','DD/MM/RR'),'28708,86');
Insert into TASA_CAMBIO (CODMONEDA,FECAMBIO,TASACAMBIO) values ('UF',to_date('16/06/20','DD/MM/RR'),'28709,82');
Insert into TASA_CAMBIO (CODMONEDA,FECAMBIO,TASACAMBIO) values ('UF',to_date('15/06/20','DD/MM/RR'),'28710,77');
Insert into TASA_CAMBIO (CODMONEDA,FECAMBIO,TASACAMBIO) values ('UF',to_date('14/06/20','DD/MM/RR'),'28711,73');
Insert into TASA_CAMBIO (CODMONEDA,FECAMBIO,TASACAMBIO) values ('UF',to_date('13/06/20','DD/MM/RR'),'28712,69');
Insert into TASA_CAMBIO (CODMONEDA,FECAMBIO,TASACAMBIO) values ('UF',to_date('12/06/20','DD/MM/RR'),'28713,65');
Insert into TASA_CAMBIO (CODMONEDA,FECAMBIO,TASACAMBIO) values ('UF',to_date('11/06/20','DD/MM/RR'),'28714,6');
Insert into TASA_CAMBIO (CODMONEDA,FECAMBIO,TASACAMBIO) values ('UF',to_date('10/06/20','DD/MM/RR'),'28715,56');
Insert into TASA_CAMBIO (CODMONEDA,FECAMBIO,TASACAMBIO) values ('UF',to_date('09/06/20','DD/MM/RR'),'28716,52');
Insert into TASA_CAMBIO (CODMONEDA,FECAMBIO,TASACAMBIO) values ('UF',to_date('08/06/20','DD/MM/RR'),'28716,52');
Insert into TASA_CAMBIO (CODMONEDA,FECAMBIO,TASACAMBIO) values ('UF',to_date('07/06/20','DD/MM/RR'),'28716,52');
Insert into TASA_CAMBIO (CODMONEDA,FECAMBIO,TASACAMBIO) values ('UF',to_date('06/06/20','DD/MM/RR'),'28716,52');
Insert into TASA_CAMBIO (CODMONEDA,FECAMBIO,TASACAMBIO) values ('UF',to_date('05/06/20','DD/MM/RR'),'28716,52');
Insert into TASA_CAMBIO (CODMONEDA,FECAMBIO,TASACAMBIO) values ('UF',to_date('04/06/20','DD/MM/RR'),'28716,52');
Insert into TASA_CAMBIO (CODMONEDA,FECAMBIO,TASACAMBIO) values ('UF',to_date('03/06/20','DD/MM/RR'),'28716,52');
Insert into TASA_CAMBIO (CODMONEDA,FECAMBIO,TASACAMBIO) values ('UF',to_date('02/06/20','DD/MM/RR'),'28716,52');
Insert into TASA_CAMBIO (CODMONEDA,FECAMBIO,TASACAMBIO) values ('UF',to_date('01/06/20','DD/MM/RR'),'28716,52');
Insert into TASA_CAMBIO (CODMONEDA,FECAMBIO,TASACAMBIO) values ('UF',to_date('31/05/20','DD/MM/RR'),'28716,52');
Insert into TASA_CAMBIO (CODMONEDA,FECAMBIO,TASACAMBIO) values ('UF',to_date('30/05/20','DD/MM/RR'),'28716,52');
Insert into TASA_CAMBIO (CODMONEDA,FECAMBIO,TASACAMBIO) values ('UF',to_date('29/05/20','DD/MM/RR'),'28716,52');
Insert into TASA_CAMBIO (CODMONEDA,FECAMBIO,TASACAMBIO) values ('UF',to_date('28/05/20','DD/MM/RR'),'28716,52');
Insert into TASA_CAMBIO (CODMONEDA,FECAMBIO,TASACAMBIO) values ('UF',to_date('27/05/20','DD/MM/RR'),'28716,52');
Insert into TASA_CAMBIO (CODMONEDA,FECAMBIO,TASACAMBIO) values ('UF',to_date('26/05/20','DD/MM/RR'),'28716,52');
Insert into TASA_CAMBIO (CODMONEDA,FECAMBIO,TASACAMBIO) values ('UF',to_date('25/05/20','DD/MM/RR'),'28716,52');
Insert into TASA_CAMBIO (CODMONEDA,FECAMBIO,TASACAMBIO) values ('UF',to_date('24/05/20','DD/MM/RR'),'28716,52');
Insert into TASA_CAMBIO (CODMONEDA,FECAMBIO,TASACAMBIO) values ('UF',to_date('23/05/20','DD/MM/RR'),'28716,52');
Insert into TASA_CAMBIO (CODMONEDA,FECAMBIO,TASACAMBIO) values ('UF',to_date('22/05/20','DD/MM/RR'),'28716,52');
Insert into TASA_CAMBIO (CODMONEDA,FECAMBIO,TASACAMBIO) values ('UF',to_date('21/05/20','DD/MM/RR'),'28716,52');
--------------------------------------------------------
--  DDL for Index PK_TASA_CAMBIO
--------------------------------------------------------

CREATE UNIQUE INDEX "PK_TASA_CAMBIO" ON "TASA_CAMBIO" ("CODMONEDA", "FECAMBIO");
--------------------------------------------------------

ALTER TABLE "TASA_CAMBIO" MODIFY ("CODMONEDA" NOT NULL ENABLE);
ALTER TABLE "TASA_CAMBIO" MODIFY ("FECAMBIO" NOT NULL ENABLE);
ALTER TABLE "TASA_CAMBIO" MODIFY ("TASACAMBIO" NOT NULL ENABLE);
ALTER TABLE "TASA_CAMBIO" ADD CONSTRAINT "PK_TASA_CAMBIO" PRIMARY KEY ("CODMONEDA", "FECAMBIO");