CREATE TABLE "CUOTA" 
(	"IDCUOTA" NUMBER(10,0), 
"IDSOCIO" NUMBER(10,0), 
"PERIODO" NUMBER(4,0), 
"MONTO_BRUTO" NUMBER(12,0), 
"MONTO_DSCTO" NUMBER(12,0), 
"MONTO_NETO" NUMBER(12,0), 
"MONTO_ABONO" NUMBER(12,0), 
"IDPAGADOR" NUMBER(10,0), 
"ESTADO" CHAR(3 BYTE), 
"OBSERVACION" VARCHAR2(255 BYTE), 
"FECRE" DATE, 
"FEMOD" DATE
);

CREATE UNIQUE INDEX "CUOTA_PK" ON "CUOTA" ("IDCUOTA");


ALTER TABLE "CUOTA" MODIFY ("IDCUOTA" NOT NULL ENABLE);
ALTER TABLE "CUOTA" MODIFY ("IDSOCIO" NOT NULL ENABLE);
ALTER TABLE "CUOTA" MODIFY ("PERIODO" NOT NULL ENABLE);
ALTER TABLE "CUOTA" MODIFY ("MONTO_BRUTO" NOT NULL ENABLE);
ALTER TABLE "CUOTA" MODIFY ("MONTO_DSCTO" NOT NULL ENABLE);
ALTER TABLE "CUOTA" MODIFY ("MONTO_NETO" NOT NULL ENABLE);
ALTER TABLE "CUOTA" MODIFY ("IDPAGADOR" NOT NULL ENABLE);
ALTER TABLE "CUOTA" MODIFY ("OBSERVACION" NOT NULL ENABLE);
ALTER TABLE "CUOTA" MODIFY ("FECRE" NOT NULL ENABLE);
ALTER TABLE "CUOTA" ADD CONSTRAINT "CUOTA_PK" PRIMARY KEY ("IDCUOTA");
